package com.glacierglimmer.endfieldchargeplus.core.model

/**
 * The built-in schemes shipped with Endfield Charge Plus.
 *
 * These are a faithful port of `CustomHudSettings.CreateDefaultProfiles()` in the Windows edition:
 * same order, same built-in keys, same templates, same icons, same colour rules and the same
 * progress variables. Ids are deterministic (`builtin.<key>`) so that a re-created built-in never
 * duplicates itself in a stored configuration, while an imported desktop configuration keeps its
 * own GUIDs.
 */
object BuiltInProfiles {

    const val BATTERY = "system.battery"
    const val CPU = "system.cpu"
    const val MEMORY = "system.memory"
    const val GPU = "system.gpu"
    const val NETWORK = "system.network"
    const val DISK = "system.disk"
    const val TIME_DAY_PROGRESS = "time.day-progress"
    const val DEEPSEEK_BALANCE = "deepseek.balance-period"
    const val NETWORK_PROBE = "network.ping"

    fun idOf(builtInKey: String): String = "builtin.$builtInKey"

    fun all(): List<HudProfile> = listOf(
        HudProfile(
            id = idOf(BATTERY),
            isBuiltIn = true,
            builtInKey = BATTERY,
            category = "系统",
            name = "电池",
            animationMode = "Full",
            taglineTemplate = "/// BATTERY",
            titleTemplate = "电池",
            primaryTemplate = "{battery.remaining_mwh|0}",
            secondaryTemplate = "/{battery.full_mwh|0}",
            rightTemplate = "{battery.percent|0}",
            rightSuffix = "%",
            progressVariable = "battery.percent",
            leftIcon = "bolt",
            rightIcon = "battery",
            colorRules = listOf(
                HudColorRule(variable = "battery.percent", operator = "<=", value = 20.0, color = "#FF4D4F"),
            ),
        ),
        HudProfile(
            id = idOf(CPU),
            isBuiltIn = true,
            builtInKey = CPU,
            category = "系统",
            name = "CPU",
            animationMode = "Full",
            taglineTemplate = "/// CPU",
            titleTemplate = "CPU",
            primaryTemplate = "{cpu.frequency_ghz|0.00}",
            secondaryTemplate = " GHz",
            rightTemplate = "{cpu.usage|0}",
            rightSuffix = "%",
            progressVariable = "cpu.usage",
            leftIcon = "cpu",
            rightIcon = "cpu",
            colorRules = listOf(
                HudColorRule(variable = "cpu.usage", operator = ">=", value = 90.0, color = "#FF4D4F"),
                HudColorRule(variable = "cpu.usage", operator = ">=", value = 75.0, color = "#FFB84D"),
            ),
        ),
        HudProfile(
            id = idOf(MEMORY),
            isBuiltIn = true,
            builtInKey = MEMORY,
            category = "系统",
            name = "内存",
            animationMode = "Full",
            taglineTemplate = "/// MEMORY",
            titleTemplate = "内存",
            primaryTemplate = "{memory.used_bytes|gb:1}",
            secondaryTemplate = "/{memory.total_bytes|gb:1} GB",
            rightTemplate = "{memory.usage|0}",
            rightSuffix = "%",
            progressVariable = "memory.usage",
            leftIcon = "memory",
            rightIcon = "memory",
        ),
        HudProfile(
            id = idOf(GPU),
            isBuiltIn = true,
            builtInKey = GPU,
            category = "系统",
            name = "GPU",
            animationMode = "Full",
            taglineTemplate = "/// GPU",
            titleTemplate = "GPU",
            primaryTemplate = "{gpu.memory_used_bytes|gb:1}",
            secondaryTemplate = "/{gpu.memory_total_bytes|gb:1} GB",
            rightTemplate = "{gpu.usage|0}",
            rightSuffix = "%",
            progressVariable = "gpu.usage",
            leftIcon = "gpu",
            rightIcon = "gpu",
        ),
        HudProfile(
            id = idOf(NETWORK),
            isBuiltIn = true,
            builtInKey = NETWORK,
            category = "系统",
            name = "网络",
            animationMode = "Full",
            taglineTemplate = "/// NETWORK",
            titleTemplate = "网络",
            primaryTemplate = "↓ {network.display_download}",
            secondaryTemplate = "  ↑ {network.display_upload}",
            rightTemplate = "{network.profile_percent_text}",
            rightSuffix = "",
            progressVariable = "network.profile_percent",
            progressMin = 0.0,
            progressMax = 100.0,
            leftIcon = "network",
            rightIcon = "network",
            networkDisplayUnit = "AutoBytes",
            networkPercentMode = "Total",
            networkReferenceValue = 500.0,
            networkReferenceUnit = "Mbps",
        ),
        HudProfile(
            id = idOf(DISK),
            isBuiltIn = true,
            builtInKey = DISK,
            category = "系统",
            name = "系统盘",
            animationMode = "Full",
            taglineTemplate = "/// SYSTEM DISK",
            titleTemplate = "系统盘",
            primaryTemplate = "{disk.system.used_bytes|gb:1}",
            secondaryTemplate = "/{disk.system.total_bytes|gb:1} GB",
            rightTemplate = "{disk.system.usage|0}",
            rightSuffix = "%",
            progressVariable = "disk.system.usage",
            leftIcon = "disk",
            rightIcon = "disk",
        ),
        HudProfile(
            id = idOf(TIME_DAY_PROGRESS),
            isBuiltIn = true,
            builtInKey = TIME_DAY_PROGRESS,
            category = "时间",
            name = "日进程",
            animationMode = "Full",
            taglineTemplate = "/// TIME",
            titleTemplate = "日进程",
            primaryTemplate = "{time.current}",
            secondaryTemplate = "",
            rightTemplate = "{time.display.status_text}",
            rightSuffix = "",
            progressVariable = "time.display.progress",
            progressMin = 0.0,
            progressMax = 100.0,
            leftIcon = "clock",
            rightIcon = "clock",
            timeTargetEnabled = false,
            timeTarget = "10:00:00",
        ),
        HudProfile(
            id = idOf(DEEPSEEK_BALANCE),
            isBuiltIn = true,
            builtInKey = DEEPSEEK_BALANCE,
            category = "DeepSeek API",
            name = "余额 / 时段",
            animationMode = "Full",
            taglineTemplate = "/// DEEPSEEK API",
            titleTemplate = "DeepSeek 当前{deepseek.period.name_zh}",
            primaryTemplate = "¥{deepseek.balance|0.00}",
            secondaryTemplate = "  {deepseek.period.remaining_text}",
            rightTemplate = "{deepseek.period.progress_text}",
            rightSuffix = "",
            progressVariable = "deepseek.period.progress",
            progressMin = 0.0,
            progressMax = 100.0,
            leftIcon = "api",
            rightIcon = "clock",
        ),
        HudProfile(
            id = idOf(NETWORK_PROBE),
            isBuiltIn = true,
            builtInKey = NETWORK_PROBE,
            category = "网络",
            name = "网络包探测器",
            animationMode = "Full",
            taglineTemplate = "/// NETWORK PROBE",
            titleTemplate = "网络包探测器",
            primaryTemplate = "{probe.latency_ms|0}ms",
            secondaryTemplate = "",
            rightTemplate = "丢包{probe.loss_percent|0}",
            rightSuffix = "%",
            progressVariable = "probe.loss_percent",
            progressMin = 0.0,
            progressMax = 100.0,
            leftIcon = "signal",
            rightIcon = "gauge",
            pingTarget = "1.1.1.1",
            probeProtocol = "ICMP",
            probePort = 443,
            colorRules = listOf(
                HudColorRule(variable = "probe.loss_percent", operator = ">=", value = 30.0, color = "#FF4D4F"),
                HudColorRule(variable = "probe.loss_percent", operator = ">=", value = 10.0, color = "#FFB84D"),
            ),
        ),
    )
}
